block navigation
VitaliyMeshechek/project-GoodFood pull request #2
Opened 2022-08-26 13:31 UTC by Inliver

Настроил блок навигации. Не прикрутил хедер к вью порту и выпадающее меню с бургер кнопкой сделаю через модалку

2022-08-27 00:03 UTC, VitaliyMeshechek requested changes

2022-08-27 00:03 UTC, VitaliyMeshechek commented on src/header.html
> +  <div class="conteiner header__conteiner">
В классе conteiner, нужно заменить букву "e" на "a". Правильно будет container. У нас в main именно так записано

2022-08-27 00:03 UTC, VitaliyMeshechek commented on src/sass/layout/_header.scss
> +    margin-bottom: 72px;
margin-bottom у нас по макету нету, там идет высота всего хедера height: 72px;

2022-08-27 00:03 UTC, VitaliyMeshechek commented on src/sass/layout/_header.scss
> +        width: 1200px;
У нас по макету width: 1280px.

2022-08-27 00:03 UTC, VitaliyMeshechek commented on src/header.html
> +    <div class="place-for-btn hide__nav-mobile">BTN</div>
кнопке нужно задать имя Order Now

2022-08-27 00:03 UTC, VitaliyMeshechek commented on src/sass/layout/_header.scss
> +    padding: 16px 10px 16px 16px;
На мобилке в сплывающем окне, дизайнер добавила крестик 24х24.

2022-08-27 00:03 UTC, VitaliyMeshechek commented on src/sass/layout/_header.scss
> +            height: 32px;
кнопке нужно задать border-radius: 30px;

2022-08-27 00:03 UTC, VitaliyMeshechek commented on src/sass/layout/_header.scss
> +    background-color: aqua;
background-color: $Button-green

2022-08-27 03:31 UTC, Inliver commented on src/header.html
> +  <div class="conteiner header__conteiner">
Исправлено

2022-08-27 03:31 UTC, Inliver commented on src/sass/layout/_header.scss
> +    margin-bottom: 72px;
Исправлено.

2022-08-27 03:31 UTC, Inliver commented on src/sass/layout/_header.scss
> +        width: 1200px;
Это общие стили  которых у меня вообще не должно быть. Исправлено

2022-08-27 03:36 UTC, Inliver commented on src/sass/layout/_header.scss
> +    padding: 16px 10px 16px 16px;
Ну начнем с того что модалки с всплывающим окном вообще пока нету а то что ты видищь это просто геометрия 
 блока навигации .............

2022-08-27 03:36 UTC, Inliver commented on src/sass/layout/_header.scss
> +            height: 32px;
Кнопки нет.

2022-08-27 03:36 UTC, Inliver commented on src/sass/layout/_header.scss
> +    background-color: aqua;
Кнопки нет

2022-08-27 10:33 UTC, Inliver commented on src/header.html
> +    <div class="place-for-btn hide__nav-mobile">BTN</div>
**class="place-for-btn** Да ее там ВООБШЕ НЕТ  это место для кнопки. Создано чисто для  отслеживания геометрии. Эта кнопка реализуется  у Марины в блоке, там же и стили вешаются. Когда  ты подтвердишь ее блок я просто дублирую ее кнопку со всем стилями  и  все работает! Ну а если не работает то допиливаю. Такая же фигня должна быть с блоком нав  в хедере и футере

2022-08-27 23:13 UTC, VitaliyMeshechek approved these changes

2022-08-27 23:16 UTC, VitaliyMeshechek approved these changes

2022-08-27 23:18 UTC, VitaliyMeshechek approved these changes

2022-08-27 23:18 UTC, VitaliyMeshechek approved these changes

2022-08-28 08:30 UTC, VitaliyMeshechek approved these changes

2022-08-28 08:30 UTC, VitaliyMeshechek approved these changes

2022-08-28 08:31 UTC, VitaliyMeshechek approved these changes

2022-08-28 08:42 UTC, VitaliyMeshechek approved these changes

2022-08-28 08:48 UTC, merged