Hero slider btn
VitaliyMeshechek/project-GoodFood pull request #5
Opened 2022-08-27 11:48 UTC by Marina-dzh

2022-08-27 14:42 UTC, VitaliyMeshechek requested changes

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/components/_button.scss
> +    background-color:#B5FF00;
Сюда дайте переменную цвета $Button-light-green

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +body {
Марина, общие сбросы, все h, стили на картинку, шрифт на body, чтобы не дублировались, нужно у Вас убрать, они у нас сохранены в главной ветке, я когда буду делать сливание, чтобы не посидел еще больше)

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        line-height: 1.17;
Если округлить, получается 1.18. Оно не существенно, но лучше сделать по макету

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +    @media screen and (min-width: $tablet) {
Здесь в принципе медиа правило можно убрать, так как на мобилке уже стоит padding-top: 60px оно же будет действовать и для таблетки

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +            line-height: 1.2;
Если округлить, получается 1.21. Оно не существенно, но лучше сделать по макету

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +            width: 503px;
Тут лучше поставить width: 502px так как в макете 502.42px, то округляется до 502, а к тому еще у "p" указано 502, чтобы оно было одинаково. Оно то не существенно, но лучше сделать как в макете.

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +            width: 502px;
Проверьте у себя в девтулзах, какой у Вас шрифт на дисктопе, показывает ли он font-size: 16px; Должен подтягивать от таблетки. Нужно посмотреть.

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        min-width: 266px;
Задайте тексту цвет через переменную

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +
Задайте тексту цвет через переменную

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        @media screen and (min-width: $desctop) {
В слове $desctop у нас была очепятка, исправили букву "c" на "k"

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        @media screen and (min-width: $desctop) {
В слове $desctop у нас была очепятка, исправили букву "c" на "k"

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        @media screen and (min-width: $desctop) {
В слове $desctop у нас была очепятка, исправили букву "c" на "k"

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        @media screen and (min-width: $desctop) {
В слове $desctop у нас была очепятка, исправили букву "c" на "k"

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +    @media screen and (min-width: $desctop) {
В слове $desctop у нас была очепятка, исправили букву "c" на "k"

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +    @media screen and (min-width: $desctop){
В слове $desctop у нас была очепятка, исправили букву "c" на "k"

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +    border-radius: 4px;
border-radius: 4px; дублируется

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +    height: 40px;
Тут нужно добавить border-radius: 8px;

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        width: 584px;
У меня по макету показывает 580px

2022-08-27 14:42 UTC, VitaliyMeshechek commented on src/sass/layout/_hero.scss
> +        width: 292px
Тут по макету у меня width: 320px; папка в макете Elipse 11

2022-08-27 15:14 UTC, Marina-dzh commented on src/sass/components/_button.scss
> +    background-color:#B5FF00;
змінено в останньому коміті

2022-08-27 15:15 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +        line-height: 1.17;
виправила

2022-08-27 15:15 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +    @media screen and (min-width: $tablet) {
змінено в останньому коміті

2022-08-27 15:15 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +            line-height: 1.2;
виправила

2022-08-27 15:16 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +    @media screen and (min-width: $desctop){
змінено в останньому коміті

2022-08-27 15:16 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +    border-radius: 4px;
виправила

2022-08-27 15:16 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +    height: 40px;
виправила

2022-08-27 15:25 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +        width: 584px;
виправила, тут вказана тільки ширина картинки, якщо додати бордер то вийде 580

2022-08-27 15:25 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +        width: 292px
тут вказана тільки ширина картинки, якщо додати бордер то вийде 320

2022-08-27 15:26 UTC, Marina-dzh commented on src/sass/layout/_hero.scss
> +body {
виправила

2022-08-27 23:40 UTC, VitaliyMeshechek requested changes

2022-08-27 23:40 UTC, VitaliyMeshechek commented on src/hero.html
> +                sizes="(min-width:1280px) 528px, (min-width:768px) 292px, 100vw" src="./images/hero/slide-1@1x_528.png "
1@1x_528.png " тут у Вас пробіл перед лапками треба забрати, може в мене потім діплой матюкатися

2022-08-28 07:53 UTC, Marina-dzh commented on src/hero.html
> +                sizes="(min-width:1280px) 528px, (min-width:768px) 292px, 100vw" src="./images/hero/slide-1@1x_528.png "
виправила

2022-08-28 09:44 UTC, VitaliyMeshechek approved these changes

2022-08-28 09:44 UTC, merged